name: Nanoleaf Control
description: Nanoleaf Control
runs:
  using: composite
  steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nanoleafapi Flask
