name: Install Kubectl
description: Installs Kubectl
runs:
  using: composite
  steps:
      - name: Install Kubectl
        shell: bash
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin