name: Install Helm
description: Installs Helm
runs:
  using: composite
  steps:
      - name: Install Helm
        shell: bash # ansible et argcomplete
        run: |
          sudo python3 -m pip install --user root 
          sudo python3 -m pip install --user root


