name: Install Helm
description: Installs Helm
runs:
  using: composite
  steps:
      - name: Install Helm
        shell: bash # ansible et argcomplete -- sudo python3 -m pip install --user ansible 
        run: |
          sudo apt install --yes python-virtualenv sshpass
          sudo adduser ansible
          su ansible
          virtualenv ansible
          source ansible/bin/activate
          pip install ansible
          pip install argcomplete
          ansible --version


