name: Install Helm
description: Installs Helm
runs:
  using: composite
  steps:
      - name: Install Helm
        shell: bash
        run: |
          sudo python3 -m pip install --user ansible
          sudo python3 -m pip install --user argcomplete


