runs:
  using: composite
  steps:
      - name: Install Kubectl
        shell: bash
        run: |
          sudo apt-get install --yes tar
          wget https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz
          tar xvf helm-v3.9.3-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin
          helm version