name: Install Python
description: Installs Python
runs:
  using: composite
  steps:
    - name: Install Python
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install python3.9