name: Install Node-Exporter
description: Installs Node-Exporter
runs:
  using: composite
  steps:
      - name: Install Node-Exporter
        shell: bash
        run: |
          apt-get update -y
          apt-get install -y prometheus-node-exporter