name: Seed Runner AKS

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  setup_config:
    name: 'Runner AKS'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Azure CLI
        uses: ./.github/actions/setup-azure-cli
        
      - name: Install Bicep
        uses: ./.github/actions/setup-bicep

      - name: Install Powershell
        uses: ./.github/actions/setup-pwsh

      - name: Install Kubectl
        uses: ./.github/actions/setup-kubectl

      - name: Install Helm
        uses: ./.github/actions/setup-helm

      - name: Install OpenSSH Client
        uses: ./.github/actions/setup-open-ssh

      - name: Install Node-Exporter
        uses: ./.github/actions/setup-node-exporter

      - name: Install Ansible
        uses: ./.github/actions/setup-ansible

      - name: Run Tests
        run : |
          bash ./tools/run-test.sh

      - name: Login to Azure Subscription
        uses: ./.github/actions/login-identity
        with:
          clientId: ${{ vars.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          tenantId: ${{ vars.TENANT_ID }}
          subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
          useCredentialsFromKeyVault: false

  iodc:
    name: Azure IODC Login
    runs-on:
      labels:
        - self-hosted
        - SynologyTest
    needs: [setup_config]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout IODC
        uses: actions/checkout@v3
      
      - name: Az Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}